### ISSUE TITLE
Add configure options to disable building GUI or engine

### ISSUE THREAD

**Issue by waltervn** [dreamchess/dreamchess#10]
This should avoid confusion like in #4.

**Comment by akien-mga** [comment]
+1, I also ran into an issue like #4 for Mageia's dreamchess package [1], where some dependencies were missing on the buildsystem but dreamchess would not complain about it.

[1] https://bugs.mageia.org/show_bug.cgi?id=16041

**Comment by waltervn** [comment]
After the switch to CMake, this is no longer relevant.
