### ISSUE TITLE
git_rev.h cannot be found 

### ISSUE THREAD

**Issue by apoleon** [dreamchess/dreamchess#12]
When building the latest tarball release of Dreamchess, 0.2.1-RC2, the build fails with an error message that src/include/git_rev.h cannot be found. The problem is that the Makefile assumes an existing Git repository which is not true for tarball releases. It would be great if git_rev.h could be included into those tarballs.

**Comment by waltervn** [comment]
The tarball does appear to contain git_rev.h though, any idea what's going on exactly?

**Comment by apoleon** [comment]
I have just downloaded the source tarball again but I cannot find git_rev.h.

**Comment by waltervn** [comment]
Are you downloading dreamchess-0.2.1-RC2.tar.gz? The other download labled "Source code" indeed does not contain the file.

**Comment by apoleon** [comment]
Yes, I downloaded the "source code" labeled one.

**Comment by waltervn** [comment]
I don't think I have any control over that download, unfortunately. It's automatically tarred by github.
