### ISSUE TITLE
White screen when changing resolutions on OS X

### ISSUE THREAD

**Issue by pawlikandreas** [dreamchess/dreamchess#15]
Dear Dreamchess-Programmers, 
thank you so much for programming and releasing Dreamchess!
Sorry for opening the issue: I am teaching Mediadesign (HTL graphische in Wien / Vienna, Austria) and I integrate DC in our program: students are asked to design new interfaces for DC (Icons for the players, figures, an background), something that we are all fond of. Many interesting designs will be finished by end of June. 
There is only one mac-only thing: I cant display beyond the resolution of 640 x 480, solely a white screen apears. Is there any chance of displaying larger resolution on osx? This would be great, because the design could be much more detailled in bigger sizes…

Thank you so much in advance, 
Andreas Pawlik

**Comment by pawlikandreas** [comment]
We d be glad if someone could help…
Thanks!

**Comment by waltervn** [comment]
Kris sent you an e-mail several weeks ago with a workaround for setting the resolution by editing the options.xml file manually. Did this not work for you?

**Comment by pawlikandreas** [comment]
Hi Walter,
well, unfortunately we did not find an "options.xml file“, neither on mac nor on pc.
We d really like to solve this – many nice designs dont look as good as they could…
Best, Andreas

**Comment by waltervn** [comment]
If the file is not there, start DreamChess, go into Configuration and then choose OK right away. The file should then be created. On Windows 10 it is located in the %APPDATA%\DreamChess folder.

**Comment by pawlikandreas** [comment]
Thank you so much. ll try that.

**Comment by pawlikandreas** [comment]
Dear Walter, is there any news on this issue? Dreamchess would be perfect for design students, 
making new skins for dreamchess, maybe we could release it to the public. 
In that sense using the max resolution on osx is crucial. Any chance?

**Comment by waltervn** [comment]
Several things have changed, so this issue may have been fixed. Unfortunately, I do not have a Mac myself, so I can't test it. If you can, try building the master branch and see if that works.

**Comment by pawlikandreas** [comment]
Dear Walter, 
changing the resolution does not work. It d be fantastic if the students could work on higher
resolutions. How do I make a built for Mac?
Thank you so much…
Andreas

**Comment by waltervn** [comment]
Hi Andreas, We're working on a new version, however, I'm not sure when it will be finished. Maybe next month.

Did you try manually editing the configuration file as mentioned earlier in this thread?

**Comment by waltervn** [comment]
We're working on releasing a new version. We hope to have it ready some time this month.

**Comment by pawlikandreas** [comment]
Great news, looking forward to it. Some nice designs are to be expected!

**Comment by pawlikandreas** [comment]
Dear Walter, thank you for mail, which makes me very happy. 
Looking forward to seeing the update, 
Andreas

**Comment by waltervn** [comment]
This should be fixed now, in 0.3.0.
