### ISSUE TITLE
Shall 0.3-GIT be packaged for Debian?

### ISSUE THREAD

**Issue by apoleon** [dreamchess/dreamchess#18]
Hi,

I am thinking about packaging version 0.3-GIT for Debian. However I'm not quite sure because the version number is a bit odd and maybe it is only a development snapshot and not intended to be released for a wider audience? Is 0.3-GIT stable?

Thank you for the clarification

**Comment by waltervn** [comment]
0.3.0-GIT is just a tag for the "git describe"-based version numbers that we're now using. It is not intended for release. Unfortunately, the GitHub user interface does not let me hide this tag from the list of releases.
