### ISSUE TITLE
Dreamchess 0.2.0 for Dreamcast :)

### ISSUE THREAD

**Issue by alessandrobrasil** [dreamchess/dreamchess#22]
Please, release for sega dreamcast! thanks

**Comment by waltervn** [comment]
Sorry... we love the Dreamcast, but we have moved on.

One thing that may be of some interest perhaps. There's a slightly modified unreleased version of 0.1.0 in branch-0-1-goat. The main addition is "easy mode". This was meant to appear on a [compilation disc](http://scratchpad.wikia.com/wiki/GOAT_Games) by GOAT Store Publishing, but AFAIK that disc never came out.
