### ISSUE TITLE
mid board pawn promotion?

### ISSUE THREAD

**Issue by hex36agon** [dreamchess/dreamchess#25]
I notice at times that a pawn is offered a promotion despite not reaching the opposing rank. This is clearly wrong.

**Comment by waltervn** [comment]
I assume you're talking about the promotion dialog popping up on obviously illegal moves? The reason for this is that the GUI has only very basic move checking capabilities. Currently, any attempt to move a pawn to the back row will open the promotion dialog. If the move is actually illegal it will then be denied by the chess engine.

All this could be better of course, but it is currently working as intended. If I misunderstood what you said, feel free to reopen the bug.
