### ISSUE TITLE
more build info

### ISSUE THREAD

**Issue by mrshampoo** [dreamchess/dreamchess#28]
the building info in the README is quit limited.
people like me are not used to CMake, so im not shure if i did it right.

this is what i did:

\#installed all dependecys (voidlinux);
xbps-install -S gcc cmake bison flex SDL2-devel SDL2_image-devel SDL2_mixer-devel expat-devel glew-devel

\#renamed and extracted the tarball;
mv 0.3.0 to 0.3.0.tar.gz
tar -xvzf 0.3.0.tar.gz

\#run cmake;
cd dreamchess-dreamchess-ebdc775
cmake  CMakeLists.txt

and then I tried to run dreamchess located at 
./dreamchess/dreamchess-dreamchess-ebdc775/dreamchess/src/dreamchess
wish unfortunatly results in a window that just disapears as quickly as it apeared.. not mutch loging to be found, just exit...

**Comment by MrSiggler** [comment]
Hey, after building, you need to run 'make install'.

**Comment by mrshampoo** [comment]
I was kinda hoping that i could make a testrun before dumping all the files in to my system.
(perhaps would be nice to see some error messages that dreamchess cant find images or something at this point.)
ok. lets test it...
ooooh coool it works!!
this is awsome, thanks man!
