### ISSUE TITLE
Not starting in Gnome on Wayland in Debian 9 Stretch

### ISSUE THREAD

**Issue by ogobeonetoo** [dreamchess/dreamchess#30]
I love this game due to the easy level.  But I'm finding it doesn't start in Gnome on Wayland in Debian 9 Stretch on one computer, a desktop, while it works fine on another, a laptop, same combination.

**Comment by waltervn** [comment]
Do you see a dreamchess.log file in ~/.dreamchess? If so, could you send it to us? Thanks.

**Comment by ogobeonetoo** [comment]
I'm sorry I did not see the email to your post until now.  I checked the .dreamchess folder and I see three files, game.001 - dated 21 Oct 2018, log.001 - dated the same and options.xml - dated 24 Jun (this year).  Which do you think is pertinent to my question?

**Comment by waltervn** [comment]
I see. What version of DreamChess are you using?

**Comment by ogobeonetoo** [comment]
Well, on the entry screen it shows v0.2.1-RC2 (0203100), and in Synaptic it has an "Installed Version" of 0.2.1-RC2-2+b2.

**Comment by waltervn** [comment]
Could you try the latest version 0.3.0 to see if the problem persists there? Version 0.3.0 should also create the dreamchess.log file.

**Comment by ogobeonetoo** [comment]
waltervn, I will get back to you within a day or so.  I'm currently updating the laptop from Stretch to Buster.  Of course as above that is not the machine in question.  It works for some reason in the laptop in Wayland, but not in the Desktop in Wayland (but does in Xorg).  But I got started with the laptop first for the upgrade.  And unfortunately it is Sunday.  I work tomorrow.  So, I will soon focus on the desktop.  I will also find out within an hour what version of DreamChess the laptop upgrades to on the laptop.  I thought apt-get did the job of upgrading to Buster, but when I tried Synaptic, it wanted to remove and install a whole bunch of files.

**Comment by waltervn** [comment]
It appears that 0.3.0 is not available in Debian at the moment.

**Comment by ogobeonetoo** [comment]
My laptop finally finished upgrading to Buster.  DreamChess' version did not change, indeed.  However, a major reason I liked to use Wayland in Stretch is that Google Earth Pro only worked in Wayland.  GE now works in Gnome classic version, at least on the laptop, probably because it actually sits on Wayland, not Xorg.  So, I don't have to switch logins to use both programs at whim.

If you keep this thread open a bit longer, I might soon have the desktop working on Buster and will be able to confirm the same result there.  Perhaps I can figure out how to load 0.3.0 early at some later point. (Hope it has more easy levels, so level 2 isn't so much of a jolt!)

**Comment by waltervn** [comment]
Unfortunately you'll need to talk to someone at Debian to get the DreamChess package updated. It's out of our control.

You could try building DreamChess yourself to get the latest version.

**Comment by waltervn** [comment]
Another thing you could perhaps try is to run 0.2.1 from a terminal window, and see if that prints out any kind of error.

**Comment by MrSiggler** [comment]
Hey, what gpu/graphics driver are you using on the computer that doesn't start the game?

**Comment by ogobeonetoo** [comment]
I upgraded Debian from 9 to 10 now on the desktop.  DreamChess is now working on  Gnome Classic, which apparently now runs on Wayland, and Gnome on Xorg.  But it does not work in just plain Gnome, which, again, is said to run on Wayland.  Just for reference, my ideal world is that Google Earth runs when DreamChess works.  But GE is also not running to that script!  It runs on Gnome (just plain) but not in the other two modes, whereas DreamChess runs in the other two modes.

> Another thing you could perhaps try is to run 0.2.1 from a terminal window, and see if that prints out any kind of error.

The following ran in Gnome (just plain - so on Wayland):

:~$ dreamchess --list-drivers
DreamChess v0.2.1-RC2 (0203100)
Available drivers:

User interface: sdlgl
:~$ dreamchess
DreamChess v0.2.1-RC2 (0203100)
ui_sdlgl.c:430: error: failed to set video mode: 1280x1024; 32 bpp; fullscreen off; 2x multisampling: Couldn't find matching GLX visual
:~$ dreamchess --fullscreen
DreamChess v0.2.1-RC2 (0203100)
ui_sdlgl.c:430: error: failed to set video mode: 1280x1024; 32 bpp; fullscreen on; 2x multisampling: Couldn't find matching GLX visual
:~$ 
`
Regarding MrSiggler's question about what driver I'm using, how would I find that out?

**Comment by ogobeonetoo** [comment]
Btw, I did not add the line-throughs above.  That's Github's doing.

**Comment by ogobeonetoo** [comment]
> DreamChess is now working on Gnome Classic, which apparently now runs on Wayland (my comment above)

I have decided that Gnome Classic cannot be running on Wayland since Synaptic asserts that it cannot run in superuser mode in Wayland, and I entered that mode in Gnome Classic.  So, again, the issue with DreamChess not working still seems to be connected to the Wayland protocol.  I guess I'll try to make the new version and see if that works.  Thank you for all your help.

**Comment by waltervn** [comment]
Could you try deleting the ~/.dreamchess/options.xml file to reset it to default settings and then running it again?

**Comment by ogobeonetoo** [comment]
Ok.  At work.  Will do that when I get home, report.

**Comment by ogobeonetoo** [comment]
> Could you try deleting the ~/.dreamchess/options.xml file to reset it to default settings and then running it again?

That was the solution!  I am at my desktop in Debian 10 Buster using Gnome which is running on Wayland.  I have Google Earth working properly on my left monitor, as it needs Wayland to do so,  and DreamChess on the right monitor, also working properly.  Best of all worlds!

Thank you very much!  Have a great day, Sir!
