### ISSUE TITLE
DreamChess abort at at "Start game" (after "New game...")

### ISSUE THREAD

**Issue by Armag67** [dreamchess/dreamchess#31]
Hello,

Since upgrade to fe9fd2e commit, DreamChess abort without any message at _"Start game"_ (after _"New game..."_) during the **"Loading please wait"** message, with no error message, neither in the terminal nor in `sudo dmesg` nor in `journalctl -b`.

(I'm on Manjaro 18.0.4, Xfce stable, kernel 4.19.66-1 with french locale, and DreamChess installed with pamac on AUR)
I have only this error message :
`ERROR: Error reading DCM file (/var/tmp/pamac-build-h2/dreamchess-git/src/dreamchess/dreamchess/src/gui/ui_sdlgl_3d.c:286)`
in ~/.dreamchess/dreamchess.log (h2 is my username)

I have already deleted the `~/.dreamchess` directory, but without success...

Thanks to take a look.

**Comment by waltervn** [comment]
Thanks for the report. We can reproduce this and are investigating. Possible workaround: run dreamchess with LC_ALL="C"

**Comment by waltervn** [comment]
This should be fixed now in d215cc6

**Comment by Armag67** [comment]
Thanks, it works.
The only thing that no longer works in the app are sound and music.

**Comment by waltervn** [comment]
Great. Closing this then. :)
