### ISSUE TITLE
Dreamchess does not work with stockfish engine

### ISSUE THREAD

**Issue by lexterror** [dreamchess/dreamchess#33]
Im trying to play against stockfish and it never moves

**Comment by waltervn** [comment]
Currently, DreamChess only supports XBoard/WinBoard engines. If you want to use a UCI engine like stockfish, you could perhaps use uci2wb or polyglot to hook it up to dreamchess, but I've never tried this myself.

UCI support for DreamChess will probably be implemented at some point, but I can't give any time frame.
