### ISSUE TITLE
dreamchess.c:568: error: failed to find a user interface driver

### ISSUE THREAD

**Issue by waltervn** [dreamchess/dreamchess#4]
Hello, i compiled dreamchess on : opensuse 12.3 : Linux voyager.site 3.7.10-1.16-desktop #1 SMP PREEMPT Fri May 31 20:21:23 UTC 2013 (97c14ba) x86_64 x86_64 x86_64 GNU/Linux.

I tried to launch the game but i get the following message :

DreamChess v0.2.0 (r577)
dreamchess.c:568: error: failed to find a user interface driver

Any idea?

thx

Original comment by: cadema

**Comment by waltervn** [comment]
This happens when one or more dependencies of the DreamChess GUI are missing (e.g. SDL). You can still build in this situation, as some people are only interested in the Dreamer chess engine.

**Comment by markroxor** [comment]
What exactly are the missing dependencies? I've encountered the same problem and would like to find a workaround.

**Comment by scpkyy** [comment]
I think it may be a matter of permissions rather than missing dependencies as it runs as root - but not as the normal user.  Running as normal user from command line gives:
dreamchess.c:568: error: failed to find a user interface driver
Run it as sudo and it opens.
