### ISSUE TITLE
Cannot connect to hoichess or pychess engines

### ISSUE THREAD

**Issue by puspamadak** [dreamchess/dreamchess#42]
Please don't mind, but I love the challenging difficulty of the hoichess and pychess engines than dreamchess. There is an option in the configurations screen to change the engine, but if I replace "dreamchess" with "hoichess" or "pychess", it complains:
```
A fatal error has occurred while communicating with the chess engine.
Please check your settings.
```
![image](https://user-images.githubusercontent.com/59383614/90342921-ab461800-e029-11ea-8175-0e1a611b2309.png)

![image](https://user-images.githubusercontent.com/59383614/90342936-cd3f9a80-e029-11ea-8f1f-f129c180aa20.png)

Is this a known issue or am I doing something wrong?

**Comment by waltervn** [comment]
In theory these should work, but they have not been tested. I think for pychess you may need to enter pychess-engine. Also, these executables need to be in your path (or you could try entering a full path).

**Comment by Puspam9876** [comment]
Thanks for the suggestions. But, entering `pychess-engine` and `/usr/games/hoichess` (the absolute path of hoichess) didn't work. Still, I get the same message.

**Comment by waltervn** [comment]
I tried pychess-engine and it seems to be working here. Does it work if you run it from a terminal? Perhaps it is not installed. On Ubuntu, the pychess package in apt does not include the standalone pychess-engine. It can be created manually by running the "create-engine.sh" script from the pychess source code (you can then copy it to /usr/local/bin or another location in the PATH).

For hoichess I made some changes in 4984bff. It should work now.

**Comment by puspamadak** [comment]
Indeed pychess-engine isn't included with the pychess package. Installed pychess-engine from source and now it works. hoichess doesn't seem to be workin, but it didn't work with hoichess (maybe in the next version it works).
