### ISSUE TITLE
Configuration does not "break"

### ISSUE THREAD

**Issue by vaeli** [dreamchess/dreamchess#43]
DreamChess won't open as it could not support multisampling. I don't see a way to disable it from command line - I see that it would it's broken, from the source of it's output, and ask whether to turn this off with some error sign; this could be the most easy for a user.

![DreamChess Bug](https://user-images.githubusercontent.com/69370220/92925032-2b4d7b00-f43a-11ea-9604-9427afc8dd53.png)

**Comment by waltervn** [comment]
Could you test this in 0.3.0?

**Comment by waltervn** [comment]
Closing stale issue.
