### ISSUE TITLE
Changed resampling + resolution on Raspbian and dreamchess flashes a window then disappears.   

### ISSUE THREAD

**Issue by kjsanders86** [dreamchess/dreamchess#44]
After changing the resampling rate (thought it would be higher resolution) dreamchess won't start.  It will flash a quick black window but  then disappears.  Thoughts?  Do I need to back out resampling in a configuration file?

Thanks,

**Comment by kjsanders86** [comment]
Is there a simple solution or should I uninstall and reinstall the app?  thx,

**Comment by waltervn** [comment]
The easiest way to get out of this would probably be to delete the configuration file (options.xml)
