### ISSUE TITLE
Saved game review

### ISSUE THREAD

**Issue by rcbrds** [dreamchess/dreamchess#47]
I love using this software. On the rare occasion I win a game, I save it.  It would be nice to be able to review the sequence of steps without the selection box covering the board making it difficult to see.

**Comment by waltervn** [comment]
With "selection box" are you referring to the menu? You should be able to use the keyboard shortcut keys 'P' and 'N' to review the steps without opening the menu.

**Comment by rcbrds** [comment]
Thanks. The P and N work great.
