### ISSUE TITLE
Save game status image does not show actual game status but turn status

### ISSUE THREAD

**Issue by UndeadDevel** [dreamchess/dreamchess#54]
Running 0.3.0-GIT on Fedora.

When saving a game the image of the game state attached to the save game slot displays the turn that was viewed when the game was saved, even if a retraction to that turn is impossible, instead of the actual game status turn (i.e. the last turn made or the last turn a retraction was possible); this makes the save picture somewhat misleading as the relevant info is not whatever I was viewing when I made the save but what I can still do in the game in terms of future turns.
Alternatively, the currently viewed turn being used as a save game image could be used when the game is already over, but not when it is still running (but then it would be nice to have some kind of label in the save game slot denoting that this saved game is over and cannot be continued, only its turns viewed).

**Comment by waltervn** [comment]
Thanks for the bug reports! We will try to look into it soon.
