### ISSUE TITLE
Need a way to see whole PGN & save location

### ISSUE THREAD

**Issue by kajukenbo** [dreamchess/dreamchess#55]
Dreamchess needs a way to see the whole PGN move list or at least make it clear where the save files are at, IMO.

My experience with Linux had me look in ~/.dreamchess but I didn't see that in the man page.

I prefer boards and pieces that look closer to USCF regulation (2D, usually) but he graphics are fine.
I would readily give up the anime characters in the corner for the whole PGN / FEN that seems to scroll off the image.

Debian 10, 64-bit.  v. 0.2.1-RC2-3

**Comment by waltervn** [comment]
I've added the saved game folder for each OS to README.md
